module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  automated_cron: 0
  block: 0
  block_content: 0
  bootstrap_layouts: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_cart: 0
  commerce_checkout: 0
  commerce_cop: 0
  commerce_order: 0
  commerce_payment: 0
  commerce_price: 0
  commerce_product: 0
  commerce_store: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  file_browser: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  layout_plugin: 0
  link: 0
  locale: 0
  mailsystem: 0
  masquerade: 0
  media_entity: 0
  media_entity_image: 0
  menu_ui: 0
  mimemail: 0
  mvbk_nm: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  prepopulate: 0
  profile: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  shortcut: 0
  state_machine: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  transliterate: 0
  update: 0
  user: 0
  views_send: 0
  views_ui: 0
  ds: 1
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  mvbk_nm_bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: nb
