theme: current
defaults:
  sender: php_mail
  formatter: mime_mail
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: nb
modules:
  commerce_order:
    receipt:
      formatter: mime_mail
      sender: php_mail
  views_send:
    direct:
      formatter: mime_mail
      sender: php_mail
